import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button, Card, Checkbox, FormGroup, InputGroup, Tag, Callout, HTMLTable} from '@blueprintjs/core';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import './style.css';

function App(){
 const [state,setState]=useState({current:null,previous:null,local:null});
 const [modules,setModules]=useState([]);const [capture,setCapture]=useState(null);
 const [form,setForm]=useState({host:'127.0.0.1',start:'20',end:'25',timeout:'0.5',authorized:false});
 const [busy,setBusy]=useState('');const [notice,setNotice]=useState(null);
 useEffect(()=>{fetch('/api/state').then(r=>r.json()).then(setState).catch(()=>setNotice({text:'Verbindung fehlgeschlagen.',ok:false}));},[]);
 useEffect(()=>{fetch('/api/modules').then(r=>r.json()).then(r=>setModules(r.modules)).catch(()=>setNotice({text:'Modulliste nicht verfügbar.',ok:false}));},[]);
 const {current:c,previous:p,local:l}=state;
 const comparable=!!(c&&p&&c.target===p.target&&JSON.stringify(c.ports)===JSON.stringify(p.ports)&&JSON.stringify(c.resolved_addresses)===JSON.stringify(p.resolved_addresses)&&c.timeout_seconds===p.timeout_seconds);
 const now=new Set(c?.open_endpoints||[]),old=new Set(comparable?p.open_endpoints:[]);
 const added=comparable?[...now].filter(x=>!old.has(x)):[],removed=comparable?[...old].filter(x=>!now.has(x)):[];
 const set=(key)=>(e)=>setForm({...form,[key]:e.target.value});
 async function post(path,data){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.error||'Anfrage fehlgeschlagen');return result;}
 async function scan(e){e.preventDefault();setBusy('scan');try{setState(await post('/api/scan',form));setNotice({text:'Scan abgeschlossen.',ok:true});}catch(e){setNotice({text:e.message,ok:false});}finally{setBusy('');}}
 async function local(){setBusy('local');try{const result=await post('/api/local',{});setState(result);setNotice({text:result.local.status==='complete'?'Lokaler Check abgeschlossen.':'Lokaler Check unvollständig.',ok:result.local.status==='complete'});}catch(e){setNotice({text:e.message,ok:false});}finally{setBusy('');}}
 async function download(){try{const response=await fetch('/api/export');if(!response.ok)throw Error('Noch kein Scan vorhanden.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`t-nocker-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setNotice({text:e.message,ok:false});}}
 async function importCapture(moduleId,e){const file=e.target.files?.[0];if(!file)return;setBusy('import');try{if(file.size>1000000)throw Error('Die Datei darf höchstens 1 MB groß sein.');const data=await post(`/api/modules/${moduleId}/run`,{text:await file.text()});setCapture(data.observation);setNotice({text:'Daten importiert.',ok:true});}catch(error){setNotice({text:error.message,ok:false});}finally{setBusy('');e.target.value='';}}
 const metric=(label,value,sub)=><Card className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></Card>;
 const head=(n,title,badge)=><div className="panel-head"><div><p className="eyebrow">{n}</p><h2>{title}</h2></div><Tag minimal>{badge}</Tag></div>;
 return <div className="workbench bp6-dark">
  <nav className="icon-rail" aria-label="Bereiche"><div className="monogram">S</div><a href="#overview" title="Übersicht" aria-label="Übersicht">◈</a><a href="#canvas" title="Netzwerk" aria-label="Netzwerk">⌘</a><a href="#inspector" title="Befunde" aria-label="Befunde">◎</a><span className="rail-spacer"/><span className="rail-led" title="Lokal verbunden"/></nav>
  <header className="command-bar" id="overview"><div className="command-brand"><b>SORS</b><span> / </span> ZUSTANDSMATRIX</div><div className="command-actions"><span className="session-indicator">■ LOKALE SITZUNG</span><Button small outlined icon="download" disabled={!c} onClick={download}>BEOBACHTUNGEN JSON</Button></div></header>
  <aside className="query-pane"><div className="pane-kicker">01 / MODUL · T-NOCKER</div><h2>Portscanner</h2><p className="pane-intro">Beobachte einen Host und halte den Umfang bewusst eng.</p>
   <form className="query-form" onSubmit={scan}><FormGroup label="ZIELSYSTEM"><InputGroup value={form.host} onChange={set('host')} required/></FormGroup><div className="field-pair"><FormGroup label="VON PORT"><InputGroup type="number" min="1" max="65535" value={form.start} onChange={set('start')} required/></FormGroup><FormGroup label="BIS PORT"><InputGroup type="number" min="1" max="65535" value={form.end} onChange={set('end')} required/></FormGroup></div><FormGroup label="TIMEOUT / SEKUNDEN"><InputGroup type="number" min="0.01" max="60" step="0.01" value={form.timeout} onChange={set('timeout')} required/></FormGroup><Checkbox checked={form.authorized} onChange={e=>setForm({...form,authorized:e.target.checked})} label="Ich bin zur Prüfung dieses Ziels berechtigt."/><Button fill intent="primary" type="submit" loading={busy==='scan'} disabled={!!busy} rightIcon="arrow-right">Scan starten</Button></form>
   <div className="query-divider"/><div className="pane-kicker">EINGESTECKTE MODULE · {modules.length}</div>{modules.map(m=><div className="source-item" key={m.id}><span className="source-symbol">■</span><div><strong>{m.name}</strong><small>{m.description}</small></div><span className="source-led active"/></div>)}<div className="query-note">Nur diese lokale Sitzung. Kein automatischer Hintergrundscan.</div>
  </aside>
  <main className="analysis-main"><div className="analysis-heading"><div><span className="pane-kicker">SORS / ZUSTANDSANSICHT</span><h1>{c?c.target:'Beobachtungsmatrix'}</h1><span className="subline">{c?`Beobachtet ${new Date(c.observed_at).toLocaleString('de-CH')} · IPv4/IPv6 TCP`:'Starte einen Scan, um Endpunkte und Veränderungen zu sehen.'}</span></div><Tag large intent={c?.status==='partial'?'warning':'none'}>{c?c.status==='complete'?'SCAN VOLLSTÄNDIG':'SCAN TEILWEISE':'KEINE BEOBACHTUNG'}</Tag></div>
   {notice&&<Callout className="work-notice" intent={notice.ok?'success':'danger'}>{notice.text}</Callout>}
   <div className="evidence-strip"><div><small>OFFENE ENDPUNKTE</small><strong>{c?c.open_endpoints.length:'—'}</strong></div><div><small>NEU SEIT VORHER</small><strong>{comparable?added.length:'—'}</strong></div><div><small>PACKET-SOCKETS</small><strong>{l?l.processes.reduce((n,x)=>n+x.sockets.length,0):'—'}</strong></div><div><small>UNTERSUCHEN</small><strong>{l?l.processes.filter(x=>x.assessment==='investigate').length:'—'}</strong></div></div>
   <section className="graph-panel" id="canvas"><div className="graph-toolbar"><span>VERBINDUNGSANSICHT</span><span>{c?`${c.open_endpoints.length} offene Endpunkte`:'Warte auf Beobachtung'}</span></div><div className="graph-canvas"><div className="graph-core"><small>ZIELHOST</small><strong>{c?.target||'127.0.0.1'}</strong><span>{c?'TCP-Scan':'Noch nicht gescannt'}</span></div><div className="graph-nodes">{c?.open_endpoints.length?c.open_endpoints.slice(0,16).map((ep,i)=><div className={'graph-node '+(added.includes(ep)?'changed':'')} key={ep}><span className="node-line"/><Tag intent={added.includes(ep)?'warning':'success'}>{ep}</Tag></div>):<div className="graph-empty">{c?'Keine offenen TCP-Endpunkte beobachtet.':'Endpunkte erscheinen nach dem ersten Scan.'}</div>}</div></div><div className="graph-footer"><span>■ Beobachtet offen</span><span>□ Nicht beobachtet ≠ geschlossen</span><span>{c?`${c.duration_seconds} s`:'—'}</span></div></section>
   <section className="timeline-panel"><div className="section-label">02 / ZUSTANDSÄNDERUNG <span>Letzte zwei vergleichbare Scans</span></div>{!comparable?<p>{p?'Scans unterscheiden sich in Ziel, Adressen, Bereich oder Timeout.':'Für einen Vergleich denselben Bereich erneut scannen.'}</p>:!added.length&&!removed.length?<p>Keine Änderung an beobachteten offenen Endpunkten.</p>:<div className="timeline-tags">{added.map(ep=><Tag key={ep} intent="success">+ {ep} neu offen</Tag>)}{removed.map(ep=><Tag key={ep} intent="warning">− {ep} nicht mehr offen beobachtet</Tag>)}</div>}</section>
   {modules.filter(m=>m.input_kind==='text_file').map(m=><section className="timeline-panel import-panel" key={m.id}><div className="section-label">03 / MODUL · {m.name.toUpperCase()} <span>Dateiimport</span></div><p>{m.description}</p><label className="file-action">Datei wählen<input type="file" accept=".tsv,.txt,.csv,text/*" disabled={!!busy} onChange={e=>importCapture(m.id,e)}/></label>{capture?.module===m.id&&<p>{m.id==='wireshark_fields'?`${capture.facts.packet_rows} Paketzeilen · ${capture.coverage.distinct_flows} Verbindungen · ${capture.facts.invalid_rows} ungültige Zeilen`:capture.subject} · {capture.status==='complete'?'vollständig':'teilweise'}</p>}</section>)}
  </main>
  <aside className="inspector" id="inspector"><div className="pane-kicker">04 / MODUL · PROZESSCHECK</div><h2>Lokaler Host</h2><p className="pane-intro">Packet-Sockets auf diesem Rechner. Der Check bezieht sich nicht auf das gewählte Netzwerkziel.</p><Button outlined fill icon="search" onClick={local} loading={busy==='local'} disabled={!!busy}>Prozesse prüfen</Button><div className="inspector-section"><div className="section-label">PRÜFSTATUS</div><div className="status-card"><span className={'status-mark '+(l?.status||'')}/><div><strong>{l?l.status==='complete'?'Vollständig':'Unvollständig':'Nicht geprüft'}</strong><small>{l?l.status==='complete'?'Sichtbare Sockets zugeordnet':`${l.inaccessible_processes||0} Prozesse nicht lesbar`:'Noch keine lokale Prüfung'}</small></div></div>{l?.unattributed_packet_socket_inodes?.length>0&&<p className="unattributed">{l.unattributed_packet_socket_inodes.length} Sockets ohne Zuordnung</p>}</div><div className="inspector-section"><div className="section-label">PROZESSOBJEKTE <span>{l?.processes.length||0}</span></div>{!l?.processes.length?<p className="muted">{l?'Keine zugeordneten Prozesse.':'Nach der Prüfung erscheinen hier Prozessdetails.'}</p>:l.processes.map(proc=><div className="entity-card" key={proc.pid}><div className="entity-title"><b>{proc.process_name||'Unbekannt'}</b><Tag minimal intent={proc.assessment==='investigate'?'warning':'none'}>{proc.assessment==='investigate'?'Untersuchen':'Inventar'}</Tag></div><small>PID {proc.pid} · {proc.sockets.length} Socket(s)</small><code>{proc.executable||'Pfad nicht lesbar'}</code><small>{proc.signals.join(', ')}</small></div>)}</div><div className="inspector-foot">Ein Packet-Socket allein ist kein Malware-Nachweis. Fehlende Rechte begrenzen die Aussage.</div></aside>
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
