import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button, Card, Checkbox, FormGroup, InputGroup, Tag, Callout, HTMLTable} from '@blueprintjs/core';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import './style.css';

function App(){
 const [state,setState]=useState({current:null,previous:null,local:null});
 const [form,setForm]=useState({host:'127.0.0.1',start:'20',end:'25',timeout:'0.5',authorized:false});
 const [busy,setBusy]=useState('');const [notice,setNotice]=useState(null);
 useEffect(()=>{fetch('/api/state').then(r=>r.json()).then(setState).catch(()=>setNotice({text:'Verbindung fehlgeschlagen.',ok:false}));},[]);
 const {current:c,previous:p,local:l}=state;
 const comparable=!!(c&&p&&c.target===p.target&&JSON.stringify(c.ports)===JSON.stringify(p.ports)&&JSON.stringify(c.resolved_addresses)===JSON.stringify(p.resolved_addresses)&&c.timeout_seconds===p.timeout_seconds);
 const now=new Set(c?.open_endpoints||[]),old=new Set(comparable?p.open_endpoints:[]);
 const added=comparable?[...now].filter(x=>!old.has(x)):[],removed=comparable?[...old].filter(x=>!now.has(x)):[];
 const set=(key)=>(e)=>setForm({...form,[key]:e.target.value});
 async function post(path,data){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.error||'Anfrage fehlgeschlagen');return result;}
 async function scan(e){e.preventDefault();setBusy('scan');try{setState(await post('/api/scan',form));setNotice({text:'Scan abgeschlossen.',ok:true});}catch(e){setNotice({text:e.message,ok:false});}finally{setBusy('');}}
 async function local(){setBusy('local');try{const result=await post('/api/local',{});setState(result);setNotice({text:result.local.status==='complete'?'Lokaler Check abgeschlossen.':'Lokaler Check unvollständig.',ok:result.local.status==='complete'});}catch(e){setNotice({text:e.message,ok:false});}finally{setBusy('');}}
 async function download(){try{const response=await fetch('/api/export');if(!response.ok)throw Error('Noch kein Scan vorhanden.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`t-nocker-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setNotice({text:e.message,ok:false});}}
 const metric=(label,value,sub)=><Card className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></Card>;
 const head=(n,title,badge)=><div className="panel-head"><div><p className="eyebrow">{n}</p><h2>{title}</h2></div><Tag minimal>{badge}</Tag></div>;
 return <div className="shell bp6-dark"><aside className="rail"><div className="brand"><span className="brand-icon">T</span><span><strong>T-Nocker</strong><small>Analysekonsole</small></span></div><div className="rail-label">ARBEITSBEREICH</div><a className="nav active" href="#overview">◈　Übersicht</a><a className="nav" href="#endpoints">⌘　Endpunkte</a><a className="nav" href="#local">◎　Lokaler Check</a><div className="rail-bottom"><b className="loop-dot"/>Lokal · 127.0.0.1<br/><small>Keine Cloud-Verbindung</small></div></aside><main id="overview"><header className="topbar"><span>Arbeitsbereich / Netzwerkbeobachtung</span><span className="mode">LIVE · LOKAL</span></header><div className="workspace"><div className="page-title"><div><p className="eyebrow">T-NOCKER / SORS</p><h1>Netzwerkzustand</h1><p>Offene TCP-Endpunkte und lokale Packet-Socket-Hinweise untersuchen.</p></div><Button outlined icon="download" disabled={!c} onClick={download}>JSON für SORS</Button></div>
 <Card className="scanbar"><form onSubmit={scan}><FormGroup label="ZIELSYSTEM"><InputGroup value={form.host} onChange={set('host')} required/></FormGroup><FormGroup label="VON PORT"><InputGroup type="number" min="1" max="65535" value={form.start} onChange={set('start')} required/></FormGroup><FormGroup label="BIS PORT"><InputGroup type="number" min="1" max="65535" value={form.end} onChange={set('end')} required/></FormGroup><FormGroup label="TIMEOUT / S"><InputGroup type="number" min="0.01" max="60" step="0.01" value={form.timeout} onChange={set('timeout')} required/></FormGroup><Button intent="primary" type="submit" loading={busy==='scan'} disabled={!!busy} rightIcon="arrow-right">TCP-Scan starten</Button><Checkbox className="consent" checked={form.authorized} onChange={e=>setForm({...form,authorized:e.target.checked})} label="Ich bin berechtigt, dieses Ziel zu prüfen."/></form></Card>
 {notice&&<Callout className="notice" intent={notice.ok?'success':'danger'}>{notice.text}</Callout>}
 <section className="metrics">{metric('OFFENE ENDPUNKTE',c?c.open_endpoints.length:'—',comparable?`${added.length} neu · ${removed.length} nicht mehr offen`:c?'Kein vergleichbarer Vorgänger':'Noch kein Scan')}{metric('SCANSTATUS',c?c.status==='complete'?'Vollständig':'Teilweise':'—',c?new Date(c.observed_at).toLocaleString('de-CH'):'Bereit')}{metric('PACKET-SOCKETS',l?l.processes.reduce((n,x)=>n+x.sockets.length,0):'—',l?l.status==='complete'?'Vollständig geprüft':`Unvollständig · ${l.inaccessible_processes||0} Prozesse`:'Nicht geprüft')}{metric('UNTERSUCHUNGSBEFUNDE',l?l.processes.filter(x=>x.assessment==='investigate').length:'—','Kein Malware-Urteil')}</section>
 <div className="panels"><Card className="panel endpoints" id="endpoints">{head('01 / NETZWERK','Endpunkte',c?.target||'Noch kein Ziel')}<div className="network-view">{c?<div className="diagram"><div className="hub"><small>ZIELSYSTEM</small><strong>{c.target}</strong></div><div className="nodes">{c.open_endpoints.length?c.open_endpoints.slice(0,20).map(ep=><Tag key={ep} className={added.includes(ep)?'new':''}>{ep}</Tag>):<Tag>Keine offenen Endpunkte beobachtet</Tag>}{c.open_endpoints.length>20&&<Tag>+{c.open_endpoints.length-20} weitere</Tag>}</div></div>:<div className="empty-message"><span className="empty-symbol">⌁</span><strong>Keine Beobachtung vorhanden</strong><p>Starte oben einen Scan. Offene Endpunkte erscheinen hier mit ihrem Ziel.</p></div>}</div><div className="table-wrap"><HTMLTable striped interactive><thead><tr><th>ENDPUNKT</th><th>BEOBACHTUNG</th><th>ÄNDERUNG</th></tr></thead><tbody>{c?.open_endpoints.map(ep=><tr key={ep}><td>{ep}</td><td><Tag intent="success" minimal>TCP offen</Tag></td><td>{comparable?added.includes(ep)?'Neu':'Bekannt':'—'}</td></tr>)}</tbody></HTMLTable>{!c?.open_endpoints.length&&<p className="row-muted">{c?'Kein offener TCP-Endpunkt beobachtet.':'Noch keine Daten'}</p>}</div></Card>
 <Card className="panel local" id="local">{head('02 / LOKALER HOST','Packet-Socket-Check','Linux /proc')}<p className="panel-explainer">Ordnet Packet-Sockets lokalen Prozessen zu. Dieser Check betrifft deinen Rechner, unabhängig vom Scanziel.</p><Button outlined onClick={local} loading={busy==='local'} disabled={!!busy} rightIcon="arrow-top-right">Lokalen Check starten</Button><div className="local-summary">{l?<Callout intent={l.status==='complete'?'none':'warning'}>{l.status==='complete'?'Sichtbare Packet-Sockets zugeordnet.':`Abdeckung unvollständig: ${l.inaccessible_processes||0} Prozesse nicht lesbar, ${l.unattributed_packet_socket_inodes?.length||0} Sockets ohne Zuordnung.`}</Callout>:<p className="row-muted">Noch keine lokale Prüfung. Ohne Administratorrechte kann die Abdeckung unvollständig sein.</p>}</div><div className="process-list">{l&&!l.processes.length&&<p className="row-muted">Keine zugeordneten Packet-Socket-Prozesse.</p>}{l?.processes.map(proc=><Card key={proc.pid} className={'process '+(proc.assessment==='investigate'?'investigate':'')}><div className="process-top"><strong>PID {proc.pid} · {proc.process_name||'Unbekannt'}</strong><Tag intent={proc.assessment==='investigate'?'warning':'none'} minimal>{proc.assessment==='investigate'?'Untersuchen':'Inventar'}</Tag></div><small>{proc.executable||'Ausführbare Datei nicht lesbar'}</small><small>{proc.sockets.length} Packet-Socket(s) · {proc.signals.join(', ')}</small></Card>)}</div></Card></div>
 <Card className="panel history">{head('03 / VERLAUF','Veränderungen','Letzte zwei Scans')}<div className="changes">{!comparable?<p className="row-muted">{p?'Scans unterscheiden sich in Ziel, Adressen, Bereich oder Timeout.':'Nach zwei vergleichbaren Scans werden Veränderungen angezeigt.'}</p>:!added.length&&!removed.length?<p className="row-muted">Keine Änderung an offenen Endpunkten.</p>:<div className="change-list">{added.map(ep=><Tag key={ep} intent="success">+ {ep} neu offen</Tag>)}{removed.map(ep=><Tag key={ep} intent="warning">− {ep} nicht mehr offen beobachtet</Tag>)}</div>}</div></Card><footer>Beobachtungen sind Momentaufnahmen. Nicht sichtbare Ports können geschlossen, gefiltert oder unerreichbar sein. Ein lokaler Indikator ist kein Infektionsnachweis.</footer></div></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
